### ISSUE TITLE
Fish Trap dont save Inventory

### ISSUE THREAD

**Issue by kaffeekirsche** [kylertlove/fish-traps#1]
The Fishing Traps dont save the Inventory if player leave the chunk

**Comment by kylertlove** [comment]
I cant reproduce that.  What version of Minecraft & fabric are you using

**Comment by kaffeekirsche** [comment]
I use Minecraft 1.14.2 and fabric-api-0.3.0+build.176 and playing on dedicate server

I have do the follow things
1. Placed Diamond Fish Trap
2. Waiting a little bit, fish trap has now fish and items in it.
3. Leav ethe chunk by entering a nether portal or logout/login

Now the fish trap inventory is empty

Images:
http://prntscr.com/nzr03g
http://prntscr.com/nzqzxd

Edit:  Found STDERR in server log after login https://gist.github.com/pandory-network/29cf29d94ea0a53b9a1a32fc144cfe4e

**Comment by kylertlove** [comment]
Thanks for the info.  I found the issue and built beta version 0.0.2.  despawning should stop now
