### ISSUE TITLE
Bait from "Fish Traps" can be cloned when "extracting" from them using the Quark mod. 

### ISSUE THREAD

**Issue by SalehGrey** [kylertlove/fish-traps#10]
![2020-04-03_15 45 32](https://user-images.githubusercontent.com/62990804/78443918-c1d56f00-7646-11ea-9472-2c7aa77573d3.png)

**Comment by SalehGrey** [comment]
1.15.2, both the Forge version of Quark and Fish Traps.

**Comment by kylertlove** [comment]
fixed for 1.16
