### ISSUE TITLE
Fabric Required in Forge?

### ISSUE THREAD

**Issue by Yourname942** [kylertlove/fish-traps#13]
For some reason I am required to enable Fabric-API in order to use Fish Traps for Forge? 

When I disable Fabric-API in my modpack, Fish Traps gets disabled
When I re-enable Fish Traps, Fabric-API gets re-enabled.

https://imgur.com/a/0nzDmcM

Minecraft 1.15.2
Forge: 31.2.36
Fabric-API: 0.17.0+build.323-1.15
Fish Traps 1.15.2-0.0.5

A Forge modpack should not be required to have Fabric installed in it. Thank you.

**Comment by kylertlove** [comment]
I dont know what the twitch launcher is looking at..  i cleared the file and re-uploaded it, so try again i guess?  the build does not require it. https://github.com/kylertlove/fish-traps/blob/master/forge/build.gradle#L89
