### ISSUE TITLE
enable vanilla fishing loot table config

### ISSUE THREAD

**Issue by kylertlove** [kylertlove/fish-traps#17]
Make it possible for the pack to pull vanilla loot tables with a config.  This would most likely break the game with other fishing mods([aquaculture](https://github.com/TeamMetallurgy/Aquaculture/blob/master/src/main/java/com/teammetallurgy/aquaculture/entity/AquaFishingBobberEntity.java#L199)) since it would pull from the same loottable making their progression too simple, but it does give people a single loot table if they want it..

**Comment by Maruhl** [comment]
Unfortunately, this mod cannot be used in combination with the current version of Aquaculture (2.1.8).

I have already asked there why this is so:
https://github.com/TeamMetallurgy/Aquaculture/issues/182

Would be cool to make this work.
At the moment I use Industrial-Foregoing the "Marine Fisher", this works.

Even if it does not currently work with other mods, the idea very is awesome, I like very much!

**Comment by thepriz** [comment]
I have created Aquaculture loot tables for Fish Traps but they don't seem to be working. Does anyone see anything wrong with them?
[fish-traps-aquaculture2-data-pack.zip](https://github.com/kylertlove/fish-traps/files/5756308/fish-traps-aquaculture2-data-pack.zip)

**Comment by thepriz** [comment]
I figured out my problem, Aquaculture changed how they do their loot tables breaking my custom loot tables for Fish Traps. I will post an updated datapack when I get it fixed.

**Comment by kylertlove** [comment]
traps are configurable to use vanilla loottables -> c89af8f
