### ISSUE TITLE
Options in fishtraps-common.toml file do not work

### ISSUE THREAD

**Issue by markygnlg** [kylertlove/fish-traps#22]
mc 1.16.3, fishtraps-0.1.2.jar, with these settings:

woodenTrapLureLevel = 9
woodenTrapLuckLevel = 9
ironTrapLureLevel = 3
ironTrapLuckLevel = 3
diamondTrapLureLevel = 3
diamondTrapLuckLevel = 3
...
shouldTrapHavePenalty = false

...there's no change to the loot tables.

I also tried 'woodenTrap[Lure&Luck]Level=1/3/9' but there was no difference; always only 4 types of fish for the wooden trap.

Similarly for the Iron trap; ironTrap[Lure&Luck]Level=3 did not give any enchanted items as in diamondTrap[Lure&Luck]Level=3.
![1@DELME_fishtraps config fail](https://user-images.githubusercontent.com/62978705/108699946-db7cef00-7555-11eb-80ce-39565ab35169.png)

**Comment by kylertlove** [comment]
The fish traps were using datapack loot_tables and so wooden and iron did not have a roll for treasure loot.  change: c89af8f
 gives you the option of a config to use datapacks like before but defaults to just use the vanilla fishing loot tables, so all 3 should have the option to receive treasure.
