### ISSUE TITLE
[Forge] Feeding baits from top hopper not working anymore

### ISSUE THREAD

**Issue by Knito58** [kylertlove/fish-traps#4]
I strongly believe this worked in the past. Putting a hopper on the top side and feeding baits to the traps.

MC 1.14.3
Forge 27.0.50
Fish-Traps 0.0.2

Can put bait manually and left a star as this mod is great.

**Comment by kylertlove** [comment]
Thanks.  version ~0.0.4~ 0.0.3 should fix this.  I thought it worked also, but maybe it was just on the fabric version

**Comment by Knito58** [comment]
Yep. Past = Fabric. Maybe I thought the same thing :)
