### ISSUE TITLE
Server Side Crash 1.15

### ISSUE THREAD

**Issue by furtabs** [kylertlove/fish-traps#8]
https://pastebin.com/xRKV8S5y

**Comment by kylertlove** [comment]
`Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap`

This is a fabric-api class that cant be found.  what version of fabric-api are you using?

**Comment by ImAK9** [comment]
Getting the same crash with **Fabric API 0.4.32 build 292**

**Comment by kylertlove** [comment]
Just downloaded 0.4.32 build 292 of fabric-api and 1.0.6 of this mod and created a new world and traps with no issues.  

I just pushed 1.0.7 which moves some of the rendering code.  Not really sure if it will fix it or not cause I cant break it but give it a try

**Comment by kylertlove** [comment]
@CrankySupertoon @AK9Official still looking to see if 1.0.7 did anything

**Comment by akhyarrh** [comment]
1.0.7 work in my test. 1.15.2. fabric-api-0.4.32+build.292-1.15
